<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIbzk2GS\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIbzk2GS/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIbzk2GS.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIbzk2GS\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIbzk2GS\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ibzk2GS',
    'container.build_id' => '97e2e215',
    'container.build_time' => 1522998928,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIbzk2GS');
